services:
  time-server:
    build: .
    container_name: fastmcp_time_server
    # If you need to run the server interactively (e.g., for STDIO):
    stdin_open: true # Equivalent to docker run -i
    tty: true        # Equivalent to docker run -t
    # To run tests instead of the default CMD, you can override the command:
    # command: ["uv", "run", "pytest", "tests/test_time_server.py"]
